// homework/react/day25/day25/src todo/components/Footer/Footer.js
import React, { Component,useEffect } from 'react'
import PubSub from 'pubsub-js'
import './Footer.css'
export default function Footer (props) {
  
    let{all,done,allDone,deleteTodos}=props
    return (
      
      <div className="todo-footer">
        <label>
          <input type="checkbox" checked={all===done} onChange={allDone}/>
        </label>
        <span>
          <span>已完成 {done}</span> / 全部 {all}
        </span>
        <button className="btn btn-danger" onClick={deleteTodos}>清除已完成任务</button>
      </div>
    )
  
}

// homework/vue/day5/vue-todo/src/Footer/index.vue
<template>
  <div class="todo-footer">
        <label>
          <input type="checkbox"/>
        </label>
        <span>
          <span></span> / 全部
        </span>
        <button class="btn btn-danger">清除已完成任务</button>
      </div>
</template>

<script>

export default {
  
name:"Footer",
props:{
obj:Object
}


 
 
}

</script>

<style>
.todo-footer {
  height: 40px;
  line-height: 40px;
  padding-left: 6px;
  margin-top: 5px;
}

.todo-footer label {
  display: inline-block;
  margin-right: 20px;
  cursor: pointer;
}

.todo-footer label input {
  position: relative;
  top: -1px;
  vertical-align: middle;
  margin-right: 5px;
}

.todo-footer button {
  float: right;
  margin-top: 5px;
}

</style>
